spring.application.name=userApps

server.port=10102
server.servlet.context-path=/v1/api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret.key=${JWT_KEY}
jwt.expiration=3600000
